apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb-deployment
  labels:
    app: mariadb
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      name: {{ .Release.Name }}-mariadb-pod
      labels:
        app: mariadb
        service: web
    spec:
      containers:
      - image: {{ .Values.mariadb.image.repository }}
        name: {{ .Release.Name }}-mariadb-container
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.mariadb.resources.limits.cpu }}
            memory: {{ .Values.mariadb.resources.limits.memory }}
          requests:
            cpu: {{ .Values.mariadb.resources.requests.cpu }}
            memory: {{ .Values.mariadb.resources.requests.memory }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mariadb.root-pass }}
        ports:
        - name: mariadb
          containerPort: 3306
        volumeMounts:
        - name: sql-script
          mountPath: /docker-entrypoint-initdb.d/mensajeria.sql
          subPath: mensajeria.sql
      volumes:
      - name: sql-script
        configMap:
          name: mariadb-config