apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
  - name: mariadb
    port: {{ .Values.mariadb.service.port }}
    targetPort: 3306
  selector:
    app: mariadb