apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-nginx-service
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  - name: service-http
    port: {{ .Values.nginx.service.port }}
    targetPort: http
  selector:
    app: {{ .Values.appname }}