apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: {{ .Values.php.service.type }}
  ports:
  - name: php
    port: {{ .Values.php.service.port }}
    targetPort: 9000
  selector:
    app: php